[".local/bin/freedesktop2launcher"]
    type = "file"
    url = "https://github.com/remigourdon/freedesktop2launcher/releases/download/v0.1.0/freedesktop2launcher-x86-64"
    executable = true

[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".local/bin/tldr"]
    type = "file"
    url = "https://github.com/dbrgn/tealdeer/releases/download/v1.5.0/tealdeer-linux-x86_64-musl"
    executable = true
[".config/fish/completions/tldr.fish"]
    type = "file"
    url = "https://github.com/dbrgn/tealdeer/releases/download/v1.5.0/completions_fish"

[".config/fish/completions/docker.fish"]
    type = "file"
    url = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/fish/docker.fish"

[".local/bin/hexyl"]
    type = "file"
    url = "https://github.com/sharkdp/hexyl/releases/download/v0.9.0/hexyl-v0.9.0-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/hexyl".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "hexyl-v0.9.0-x86_64-unknown-linux-gnu/hexyl"]

[".local/bin/watchexec"]
    type = "file"
    url = "https://github.com/watchexec/watchexec/releases/download/cli-v1.18.12/watchexec-1.18.12-x86_64-unknown-linux-gnu.tar.xz"
    executable = true
    [".local/bin/watchexec".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--xz", "--to-stdout", "watchexec-1.18.12-x86_64-unknown-linux-gnu/watchexec"]

[".local/bin/lf"]
    type = "file"
    url = "https://github.com/gokcehan/lf/releases/download/r27/lf-linux-amd64.tar.gz"
    executable = true
    [".local/bin/lf".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lf"]

[".local/bin/cliphist"]
    type = "file"
    url = "https://github.com/sentriz/cliphist/releases/download/v0.3.1/v0.3.1-linux-amd64"
    executable = true

[".local/bin/tokei"]
    type = "file"
    url = "https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-i686-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/tokei".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "tokei"]

[".local/bin/procs"]
    type = "file"
    url = "https://github.com/dalance/procs/releases/download/v0.13.2/procs-v0.13.2-x86_64-linux.zip"
    executable = true
    [".local/bin/procs".filter]
        command = ",unzip-from-stdin"
        args = ["procs"]

[".local/bin/rq"]
    type = "file"
    url = "https://github.com/dflemstr/rq/releases/download/v1.0.2/rq-v1.0.2-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/rq".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "rq"]

[".local/bin/glow"]
    type = "file"
    url = "https://github.com/charmbracelet/glow/releases/download/v1.4.1/glow_1.4.1_linux_x86_64.tar.gz"
    executable = true
    [".local/bin/glow".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "glow"]
