[".local/bin/freedesktop2launcher"]
    type = "file"
    url = "https://github.com/remigourdon/freedesktop2launcher/releases/download/v0.1.0/freedesktop2launcher-x86-64"
    executable = true

[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".local/bin/tldr"]
    type = "file"
    url = "https://github.com/dbrgn/tealdeer/releases/download/v1.6.1/tealdeer-linux-x86_64-musl"
    executable = true
[".config/fish/completions/tldr.fish"]
    type = "file"
    url = "https://github.com/dbrgn/tealdeer/releases/download/v1.6.1/completions_fish"

[".config/fish/completions/docker.fish"]
    type = "file"
    url = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/fish/docker.fish"

[".local/bin/zellij"]
    type = "file"
    url = "https://github.com/zellij-org/zellij/releases/download/v0.38.2/zellij-x86_64-unknown-linux-musl.tar.gz"
    executable = true
    [".local/bin/zellij".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zellij"]

[".local/bin/hexyl"]
    type = "file"
    url = "https://github.com/sharkdp/hexyl/releases/download/v0.12.0/hexyl-v0.12.0-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/hexyl".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "hexyl-v0.12.0-x86_64-unknown-linux-gnu/hexyl"]

[".local/bin/lazydocker"]
    type = "file"
    url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.21.1/lazydocker_0.21.1_Linux_x86_64.tar.gz"
    executable = true
    [".local/bin/lazydocker".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazydocker"]

[".local/bin/systeroid"]
    type = "file"
    url = "https://github.com/orhun/systeroid/releases/download/v0.4.1/systeroid-0.4.1-x86_64-unknown-linux-gnu_all-features.tar.gz"
    executable = true
    [".local/bin/systeroid".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "systeroid-0.4.1/systeroid"]
[".local/bin/systeroid-tui"]
    type = "file"
    url = "https://github.com/orhun/systeroid/releases/download/v0.4.1/systeroid-0.4.1-x86_64-unknown-linux-gnu_all-features.tar.gz"
    executable = true
    [".local/bin/systeroid-tui".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "systeroid-0.4.1/systeroid-tui"]

[".local/bin/nu"]
    type = "file"
    url = "https://github.com/nushell/nushell/releases/download/0.79.0/nu-0.79.0-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/nu".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "nu-0.79.0-x86_64-unknown-linux-gnu/nu"]

[".local/bin/watchexec"]
    type = "file"
    url = "https://github.com/watchexec/watchexec/releases/download/v1.22.2/watchexec-1.22.2-x86_64-unknown-linux-gnu.tar.xz"
    executable = true
    [".local/bin/watchexec".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--xz", "--to-stdout", "watchexec-1.22.2-x86_64-unknown-linux-gnu/watchexec"]

[".local/bin/lnav"]
    type = "file"
    url = "https://github.com/tstack/lnav/releases/download/v0.11.1/lnav-0.11.1-x86_64-linux-musl.zip"
    executable = true
    [".local/bin/lnav".filter]
        command = ",unzip-from-stdin"
        args = ["lnav-0.11.1/lnav"]

[".local/bin/duckdb"]
    type = "file"
    url = "https://github.com/duckdb/duckdb/releases/download/v0.8.1/duckdb_cli-linux-amd64.zip"
    executable = true
    [".local/bin/duckdb".filter]
        command = ",unzip-from-stdin"
        args = ["duckdb"]

[".local/bin/lf"]
    type = "file"
    url = "https://github.com/gokcehan/lf/releases/download/r29/lf-linux-amd64.tar.gz"
    executable = true
    [".local/bin/lf".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lf"]

[".local/bin/cliphist"]
    type = "file"
    url = "https://github.com/sentriz/cliphist/releases/download/v0.4.0/v0.4.0-linux-amd64"
    executable = true

[".local/bin/tokei"]
    type = "file"
    url = "https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-i686-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/tokei".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "tokei"]

[".local/bin/procs"]
    type = "file"
    url = "https://github.com/dalance/procs/releases/download/v0.14.0/procs-v0.14.0-x86_64-linux.zip"
    executable = true
    [".local/bin/procs".filter]
        command = ",unzip-from-stdin"
        args = ["procs"]

[".local/bin/glow"]
    type = "file"
    url = "https://github.com/charmbracelet/glow/releases/download/v1.5.0/glow_1.5.0_linux_x86_64.tar.gz"
    executable = true
    [".local/bin/glow".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "glow"]

[".local/bin/up"]
    type = "file"
    url = "https://github.com/akavel/up/releases/download/v0.4/up"
    executable = true

[".local/bin/gron"]
    type = "file"
    url = "https://github.com/tomnomnom/gron/releases/download/v0.7.1/gron-linux-amd64-0.7.1.tgz"
    executable = true
    [".local/bin/gron".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "gron"]
