[".local/bin/freedesktop2launcher"]
    type = "file"
    url = "https://github.com/remigourdon/freedesktop2launcher/releases/download/v0.1.0/freedesktop2launcher-x86-64"
    executable = true

[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".local/bin/tldr"]
    type = "file"
    url = "https://github.com/dbrgn/tealdeer/releases/download/v1.6.1/tealdeer-linux-x86_64-musl"
    executable = true
[".config/fish/completions/tldr.fish"]
    type = "file"
    url = "https://github.com/dbrgn/tealdeer/releases/download/v1.6.1/completions_fish"

[".config/fish/completions/docker.fish"]
    type = "file"
    url = "https://raw.githubusercontent.com/docker/cli/master/contrib/completion/fish/docker.fish"

[".local/bin/zellij"]
    type = "file"
    url = "https://github.com/zellij-org/zellij/releases/download/v0.39.2/zellij-x86_64-unknown-linux-musl.tar.gz"
    executable = true
    [".local/bin/zellij".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zellij"]

[".local/bin/hexyl"]
    type = "file"
    url = "https://github.com/sharkdp/hexyl/releases/download/v0.13.1/hexyl-v0.13.1-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/hexyl".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "hexyl-v0.13.1-x86_64-unknown-linux-gnu/hexyl"]

[".local/bin/lazydocker"]
    type = "file"
    url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.23.1/lazydocker_0.23.1_Linux_x86_64.tar.gz"
    executable = true
    [".local/bin/lazydocker".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazydocker"]

[".local/bin/systeroid"]
    type = "file"
    url = "https://github.com/orhun/systeroid/releases/download/v0.4.4/systeroid-0.4.4-x86_64-unknown-linux-gnu_all-features.tar.gz"
    executable = true
    [".local/bin/systeroid".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "systeroid-0.4.4/systeroid"]
[".local/bin/systeroid-tui"]
    type = "file"
    url = "https://github.com/orhun/systeroid/releases/download/v0.4.4/systeroid-0.4.4-x86_64-unknown-linux-gnu_all-features.tar.gz"
    executable = true
    [".local/bin/systeroid-tui".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "systeroid-0.4.4/systeroid-tui"]

[".local/bin/nu"]
    type = "file"
    url = "https://github.com/nushell/nushell/releases/download/0.92.1/nu-0.92.1-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/nu".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "nu-0.92.1-x86_64-unknown-linux-gnu/nu"]

[".local/bin/watchexec"]
    type = "file"
    url = "https://github.com/watchexec/watchexec/releases/download/v1.24.1/watchexec-1.24.1-x86_64-unknown-linux-gnu.tar.xz"
    executable = true
    [".local/bin/watchexec".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--xz", "--to-stdout", "watchexec-1.24.1-x86_64-unknown-linux-gnu/watchexec"]

[".local/bin/lnav"]
    type = "file"
    url = "https://github.com/tstack/lnav/releases/download/v0.11.2/lnav-0.11.2-x86_64-linux-musl.zip"
    executable = true
    [".local/bin/lnav".filter]
        command = ",unzip-from-stdin"
        args = ["lnav-0.11.2/lnav"]

[".local/bin/lf"]
    type = "file"
    url = "https://github.com/gokcehan/lf/releases/download/r31/lf-linux-amd64.tar.gz"
    executable = true
    [".local/bin/lf".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lf"]

[".local/bin/cliphist"]
    type = "file"
    url = "https://github.com/sentriz/cliphist/releases/download/v0.4.0/v0.4.0-linux-amd64"
    executable = true

[".local/bin/tokei"]
    type = "file"
    url = "https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-i686-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/tokei".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "tokei"]

[".local/bin/procs"]
    type = "file"
    url = "https://github.com/dalance/procs/releases/download/v0.14.4/procs-v0.14.4-x86_64-linux.zip"
    executable = true
    [".local/bin/procs".filter]
        command = ",unzip-from-stdin"
        args = ["procs"]

[".local/bin/glow"]
    type = "file"
    url = "https://github.com/charmbracelet/glow/releases/download/v1.5.1/glow_Linux_x86_64.tar.gz"
    executable = true
    [".local/bin/glow".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "glow"]

[".local/bin/up"]
    type = "file"
    url = "https://github.com/akavel/up/releases/download/v0.4/up"
    executable = true

[".local/bin/gron"]
    type = "file"
    url = "https://github.com/tomnomnom/gron/releases/download/v0.7.1/gron-linux-amd64-0.7.1.tgz"
    executable = true
    [".local/bin/gron".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "gron"]

[".local/bin/ast-grep"]
    type = "file"
    url = "https://github.com/ast-grep/ast-grep/releases/download/0.14.3/sg-x86_64-unknown-linux-gnu.zip"
    executable = true
    [".local/bin/ast-grep".filter]
        command = ",unzip-from-stdin"
        args = ["sg"]

[".local/bin/trip"]
    type = "file"
    url = "https://github.com/fujiapple852/trippy/releases/download/0.9.0/trippy-0.9.0-x86_64-unknown-linux-gnu.tar.gz"
    executable = true
    [".local/bin/trip".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "trippy-0.9.0-x86_64-unknown-linux-gnu/trip"]

