#!/bin/sh

# Set default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="lf"

# Start X11 server if i3 is not already running
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x i3 >/dev/null && exec startx

# lf
LFCD="$GOPATH/src/github.com/gokcehan/lf/etc/lfcd.sh"
[ -f "$LFCD" ] && . "$LFCD"

# Scripts
SCRIPTSPATH="${HOME}/.scripts"
[ -d "${SCRIPTSPATH}" ] && export PATH="$PATH:${SCRIPTSPATH}"

# Go
export GOPATH="${HOME}/.go"
[ -d "${GOPATH}" ] && export PATH="$PATH:${GOPATH}/bin"

# Rust
RUSTPATH="${HOME}/.cargo"
[ -d "${RUSTPATH}" ] && export PATH="$PATH:${RUSTPATH}/bin"

# Local binaries
[ -d "${HOME}/.local/bin" ] && export PATH="$PATH:${HOME}/.local/bin"

# Load bashrc
echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && . "${HOME}/.bashrc"
