#!/bin/sh

# Load Xresources
[ -e ~/.Xresources ] && xrdb ~/.Xresources

# Set keyboard layout and variant
localectl set-x11-keymap us pc105 altgr-intl ctrl:swapcap

# Reload last pywal colorscheme
wal -R

# Start udiskie
udiskie &

# Start i3
exec i3
