#!/bin/sh

# Load Xresources
[ -e ~/.Xresources ] && xrdb ~/.Xresources

# Set keyboard layout and variant
setxkbmap -layout us -variant altgr-intl

# Reload last pywal colorscheme
wal -R

# Start udiskie
udiskie &

# Start i3
exec i3
